### ISSUE TITLE
Permitir que el texto sea editable mediante una opcion

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/yomiyasu#117]
Hay veces que el ocr falla y uno quiere editarlo rapidamente para poder usar yomichan en la misma pagina y no abrir otra.
Seria bueno tambien si, se puede descargar el html modificado con un boton en vez de tener que guardarlo con click secundario para poder enviarte el html corregido.

**Comment by alexay7** [comment]
No puedo permitir que hagáis cambios permanentes a los archivos ni, sinceramente, tampoco quiero asumir el trabajo de resubir cosas cada vez que encontréis un fallo del OCR...
