### ISSUE TITLE
Hacer la indicacion del tiempo mas grande

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/yomiyasu#186]
![image](https://github.com/alexay7/yomiyasu/assets/119679067/3cb17b23-699e-416d-a0d6-722b0f683637)
Practicamente no se ve xd

**Comment by alexay7** [comment]
La idea de ese indicador es que de un vistazo puedas saber si está activo o no pero que el resto del tiempo no sepas que existe así que la idea es que no se vea. Miraré de hacerlo ligeramente en fondos oscuros
