### ISSUE TITLE
Aumentar el tamaño de las letras en las novelas

### ISSUE THREAD

**Issue by DnielFort** [alexay7/yomiyasu#187]
Al menos en mi equipo se ven los caracteres muy pequeños, se vuelve muy difícil el leer.

**Comment by alexay7** [comment]
Esa configuración la tienes que personalizar tú en los ajustes de ttu dentro de la propia página de la novela

![image](https://github.com/alexay7/yomiyasu/assets/43906716/38a69ea0-bd2d-4b40-b472-0defdd2b9bcf)
![image](https://github.com/alexay7/yomiyasu/assets/43906716/7f86af46-7736-4947-aef7-f94d9f08a7cf)
