### ISSUE TITLE
Opción de guardar palabras para verlas luego

### ISSUE THREAD

**Issue by alexay7** [alexay7/yomiyasu#66]
Hacer parecido al kindle, permitir guardar palabras que te llamen la atención/desconozcas y poder verlas luego en una lista para hacer con ellas lo que quieras.

Que funcione con el local storage mejor que con base de datos.

Diccionario integrado (sin la opción de añadir la palabra)

**Comment by TriDyE** [comment]
Leñe, si, eso mola.

**Comment by SirGram** [comment]
Seria viable un puntero con referencia a la hoja del vol en el que la has visto?

**Comment by alexay7** [comment]
> Seria viable un puntero con referencia a la hoja del vol en el que la has visto?

Es viable pero hacer click implicaría crear un nuevo progreso/modificar el progreso actual de ese volumen. No veo que sea muy aconsejable hacer eso.

**Comment by alexay7** [comment]
Una posible solución sería activar un modo "incognito" en el que no se guarde el progreso de esa sesión.
