### ISSUE TITLE
Arreglar Mangas apareciendo en tu tablero aunque no lo hayas empezado

### ISSUE THREAD

**Issue by Pedrubik2000** [alexay7/yomiyasu#92]
Como dice el titulo hay dos casos en los cuales estan apareciendo en mi tablero.
El primer caso es con una que esta en la lista de lectura que aparece el segundo volumen aunque no lo haya empezado.
Y el segundo caso es con una que no esta en la lista de lectura que aparece el primer volumen aunque no lo haya empezado.
![chrome_2ZtSbdtY9u](https://github.com/alexay7/tfg/assets/119679067/8150ec1e-a51d-460d-8a2d-48d80ff5cfdc)

**Comment by alexay7** [comment]
El bug está solucionado, solo falta paliar los efectos que tuvo hasta arreglarlo. Cerraré el issue cuando lo haya hecho.
